import Card from "./Card";
import Contact from "./Contact";
import CourseCards from "./CourseCards";
import Courses from "./Courses";
import Footer from "./Footer";
import Introduction from "./Introduction";
import Navbar from "./Navbar";
import Slideshow from "./Slideshow";
import TestimonialCard from "./TestimonialCard";
import Home from './Home';
export {Card,Contact,CourseCards,Courses,Footer,Home,Introduction,Navbar,Slideshow,TestimonialCard};